export const tsanganLayout = [
	[
		// Row: alpha row
		{
			keyLabel: 'Esc',
			keyValue: 'Escape',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: true,
		},
		{
			keyLabel: '1',
			keyValue: '1',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '2',
			keyValue: '2',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '3',
			keyValue: '3',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '4',
			keyValue: '4',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '5',
			keyValue: '5',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '6',
			keyValue: '6',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '7',
			keyValue: '7',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '8',
			keyValue: '8',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '9',
			keyValue: '9',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '0',
			keyValue: '0',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '-',
			keyValue: '-',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '=',
			keyValue: '=',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Del',
			keyValue: 'Delete',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Bksp',
			keyValue: 'Backspace',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
	[
		// Row: Tab + Q-P
		{
			keyLabel: 'Tab',
			keyValue: 'Tab',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'q',
			keyValue: 'q',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'w',
			keyValue: 'w',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'e',
			keyValue: 'e',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'r',
			keyValue: 'r',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 't',
			keyValue: 't',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'y',
			keyValue: 'y',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'u',
			keyValue: 'u',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'i',
			keyValue: 'i',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'o',
			keyValue: 'o',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'p',
			keyValue: 'p',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '[',
			keyValue: '[',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ']',
			keyValue: ']',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '\\',
			keyValue: '\\',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
	[
		// Row: Caps / A - L / Enter
		{
			keyLabel: 'CapsLock',
			keyValue: 'CapsLock',
			keyLength: 1.75,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'a',
			keyValue: 'a',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 's',
			keyValue: 's',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'd',
			keyValue: 'd',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'f',
			keyValue: 'f',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'g',
			keyValue: 'g',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'h',
			keyValue: 'h',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'j',
			keyValue: 'j',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'k',
			keyValue: 'k',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'l',
			keyValue: 'l',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ';',
			keyValue: ';',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: "'",
			keyValue: "'",
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Ent',
			keyValue: 'Enter',
			keyLength: 2.25,
			keyType: 'mod',
			keyAccentAvailable: true,
		},
	],
	[
		// Row: Shift / Z - M / Shift
		{
			keyLabel: 'Shift',
			keyValue: 'Shift',
			keyLength: 2.25,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'z',
			keyValue: 'z',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'x',
			keyValue: 'x',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'c',
			keyValue: 'c',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'v',
			keyValue: 'v',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'b',
			keyValue: 'b',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'n',
			keyValue: 'n',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'm',
			keyValue: 'm',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ',',
			keyValue: ',',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '.',
			keyValue: '.',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '/',
			keyValue: '/',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Shift',
			keyValue: 'Shift',
			keyLength: 1.75,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Fn',
			keyValue: 'Fn',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		}, // Fn usually has no event.key
	],
	[
		// Row: Bottom mods
		{
			keyLabel: 'Ctrl',
			keyValue: 'Control',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Win',
			keyValue: 'Meta',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Alt',
			keyValue: 'Alt',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: '',
			keyValue: ' ',
			keyLength: 7,
			keyType: 'mod',
			keyAccentAvailable: true,
		}, // Spacebar
		{
			keyLabel: 'AltGr',
			keyValue: 'AltGraph',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Win',
			keyValue: 'Meta',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: 'Ctrl',
			keyValue: 'Control',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
];
