export const tsanganLayout = [
	[
		// Row: alpha row
		{
			keyLabel: ['Esc'],
			keyValue: 'Escape',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: true,
		},
		{
			keyLabel: ['!', '1'],
			keyValue: '1',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['@', '2'],
			keyValue: '2',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['#', '3'],
			keyValue: '3',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['$', '4'],
			keyValue: '4',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['%', '5'],
			keyValue: '5',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['^', '6'],
			keyValue: '6',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['&', '7'],
			keyValue: '7',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['*', '8'],
			keyValue: '8',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['(', '9'],
			keyValue: '9',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: [')', '0'],
			keyValue: '0',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['_', '-'],
			keyValue: '-',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['+', '='],
			keyValue: '=',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['|', '\\'],
			keyValue: '\\',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Del'],
			keyValue: 'Delete',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
	[
		// Row: Tab + Q-P
		{
			keyLabel: ['Tab'],
			keyValue: 'Tab',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Q'],
			keyValue: 'q',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['W'],
			keyValue: 'w',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['E'],
			keyValue: 'e',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['R'],
			keyValue: 'r',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['T'],
			keyValue: 't',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Y'],
			keyValue: 'y',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['U'],
			keyValue: 'u',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['I'],
			keyValue: 'i',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['O'],
			keyValue: 'o',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['P'],
			keyValue: 'p',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['{', '['],
			keyValue: '[',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['}', ']'],
			keyValue: ']',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Bksp'],
			keyValue: 'Backspace',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
	[
		// Row: Caps / A - L / Enter
		{
			keyLabel: ['CapsLock'],
			keyValue: 'CapsLock',
			keyLength: 1.75,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['A'],
			keyValue: 'a',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['S'],
			keyValue: 's',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['D'],
			keyValue: 'd',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['F'],
			keyValue: 'f',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['G'],
			keyValue: 'g',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['H'],
			keyValue: 'h',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['J'],
			keyValue: 'j',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['K'],
			keyValue: 'k',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['L'],
			keyValue: 'l',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: [':', ';'],
			keyValue: ';',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['"', "'"],
			keyValue: "'",
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Enter'],
			keyValue: 'Enter',
			keyLength: 2.25,
			keyType: 'mod',
			keyAccentAvailable: true,
		},
	],
	[
		// Row: Shift / Z - M / Shift
		{
			keyLabel: ['Shift'],
			keyValue: 'Shift',
			keyCode: 'ShiftLeft',
			keyLength: 2.25,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Z'],
			keyValue: 'z',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['X'],
			keyValue: 'x',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['C'],
			keyValue: 'c',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['V'],
			keyValue: 'v',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['B'],
			keyValue: 'b',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['N'],
			keyValue: 'n',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['M'],
			keyValue: 'm',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['<', ','],
			keyValue: ',',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['>', '.'],
			keyValue: '.',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['?', '/'],
			keyValue: '/',
			keyLength: 1,
			keyType: 'alpha',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Shift'],
			keyValue: 'Shift',
			keyCode: 'ShiftRight',
			keyLength: 1.75,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Fn'],
			keyValue: 'Fn',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
	[
		// Row: Bottom mods
		{
			keyLabel: ['Ctrl'],
			keyValue: 'Control',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Win'],
			keyValue: 'Meta',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Alt'],
			keyValue: 'Alt',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: [],
			keyValue: ' ',
			keyLength: 7,
			keyType: 'mod',
			keyAccentAvailable: true,
		},
		{
			keyLabel: ['AltGr'],
			keyValue: 'AltGraph',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Win'],
			keyValue: 'Meta',
			keyLength: 1,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
		{
			keyLabel: ['Ctrl'],
			keyValue: 'Control',
			keyLength: 1.5,
			keyType: 'mod',
			keyAccentAvailable: false,
		},
	],
];
